// docs/.vitepress/examples/solidjs/useField.tsx
import { createSignal, onCleanup } from 'solid-js'
import { effect } from 'alien-signals'

/**
 * Creates field state using SolidJS signals
 * @param {FormController} formController - The form controller instance
 * @param {string} fieldPath - The path to the field
 * @returns {Object} Field state and handlers
 */
export function useField(formController, fieldPath) {
  // Create reactive signals
  const [value, setValue] = createSignal(formController.getValue(fieldPath))
  const [errors, setErrors] = createSignal(formController.getErrors()[fieldPath] || [])
  const [hasErrors, setHasErrors] = createSignal((formController.getErrors()[fieldPath] || []).length > 0)

  const field = formController.field(fieldPath)
  const effects = []

  // Watch for changes to this specific field only
  effects.push(effect(() => {
    field.valueUpdated() // Subscribe to field-specific value changes
    setValue(() => formController.getValue(fieldPath))
  }))

  // Watch for errors on this specific field
  effects.push(effect(() => {
    formController.errorsChanged() // Subscribe to errors changes
    const fieldErrors = formController.getErrors()[fieldPath] || []
    setErrors(fieldErrors)
    setHasErrors(fieldErrors.length > 0)
  }))

  // Cleanup effects
  onCleanup(() => {
    effects.forEach(dispose => dispose?.())
  })

  // Handlers
  const handleInput = (inputValue) => {
    formController.setValue(fieldPath, inputValue, {
      touched: true,
      dirty: false
    })
  }

  const handleChange = (inputValue) => {
    formController.setValue(fieldPath, inputValue, {
      touched: true,
      dirty: true
    })
  }

  return {
    value,
    errors,
    hasErrors,
    handleInput,
    handleChange
  }
}

// docs/.vitepress/examples/reactjs/useField.jsx
import { useEffect, useState, useCallback } from 'react'
import { effect } from 'alien-signals'

/**
 * React hook for managing individual form fields
 * @param {FormController} formController - The form controller instance
 * @param {string} fieldPath - The path to the field
 * @returns {Object} Field state and handlers
 */
export function useField(formController, fieldPath) {
  const [fieldState, setFieldState] = useState({
    value: formController.getValue(fieldPath),
    errors: formController.getErrors()[fieldPath] || [],
    hasErrors: (formController.getErrors()[fieldPath] || []).length > 0
  })

  useEffect(() => {
    const effects = []
    const field = formController.field(fieldPath)

    // Watch for changes to this specific field only
    effects.push(effect(() => {
      field.valueUpdated() // Subscribe to field-specific value changes
      setFieldState(prev => ({
        ...prev,
        value: formController.getValue(fieldPath)
      }))
    }))

    // Watch for errors on this specific field
    effects.push(effect(() => {
      formController.errorsChanged() // Subscribe to errors changes
      const errors = formController.getErrors()[fieldPath] || []
      setFieldState(prev => ({
        ...prev,
        errors,
        hasErrors: errors.length > 0
      }))
    }))

    // Cleanup effects on unmount
    return () => {
      effects.forEach(dispose => dispose?.())
    }
  }, [formController, fieldPath])

  const handleInput = useCallback((inputValue) => {
    formController.setValue(fieldPath, inputValue, {
      touched: true,
      dirty: false
    })
  }, [formController, fieldPath])

  const handleChange = useCallback((inputValue) => {
    formController.setValue(fieldPath, inputValue, {
      touched: true,
      dirty: true
    })
  }, [formController, fieldPath])

  return {
    value: fieldState.value,
    errors: fieldState.errors,
    hasErrors: fieldState.hasErrors,
    handleInput,
    handleChange
  }
}
